### ISSUE TITLE
Develop an NR1 app in NR1 using VS Code Containers

### ISSUE THREAD

**Issue by tangollama** [newrelic/open-source-office#1]
Developing an NR1 app within NR1 using a VS Code remote Container https://code.visualstudio.com/docs/remote/containers

**Comment by devfreddy** [comment]
Related - https://github.com/newrelic/nr1-workshop/issues/83

**Comment by tangollama** [comment]
With the advent of Code spaces in GitHub, this effort feels less relevant.
