### ISSUE TITLE
Build v. 1 Double Sidebar Layout Nerdpack

### ISSUE THREAD

**Issue by tangollama** [newrelic/open-source-office#3]
- [x] Layout components
- [ ] Default configuration modal

![double_sidebar_layout](https://user-images.githubusercontent.com/929261/69676198-43503b80-106e-11ea-8152-dc1e7f004383.png)

**Comment by danielgolden** [comment]
Lots of progress here: https://github.com/newrelic/nr1-nerdpack-layout-double-sidebar
