### ISSUE TITLE
Build v. 1 T-Bone Layout Nerdpack

### ISSUE THREAD

**Issue by tangollama** [newrelic/open-source-office#4]
- [x] Layout components
- [ ] Default configuration modal

![tbone_layout](https://user-images.githubusercontent.com/929261/69676303-7692ca80-106e-11ea-8290-ee7d456bb0ad.png)

**Comment by danielgolden** [comment]
Repo and update here: https://github.com/newrelic/nr1-nerdpack-layout-t-bone
